spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/planmanagementtestdb'
    username: root
    password: Jinesh@123
  jpa:
    show_sql: false
    hibernate:
      ddl-auto: update
